"""Domain exceptions module."""

from src.domain.exceptions.domain_exceptions import (
    BrokerConnectionError,
    BrokerError,
    DataError,
    DataNotFoundError,
    DomainError,
    InsufficientCapitalError,
    InvalidDataError,
    InvalidFeatureError,
    InvalidOperationError,
    InvalidOrderError,
    InvalidPriceError,
    InvalidQuantityError,
    ModelError,
    ModelNotTrainedError,
    OrderExecutionError,
    PositionNotFoundError,
    RiskLimitExceededError,
    TradingError,
)
from src.domain.exceptions.macro_score_exceptions import (
    ContractResolutionError,
    InsufficientDataError,
    MacroScoreError,
    SymbolNotAvailableError,
)
from src.domain.exceptions.risco_externo_exceptions import (
    ErroRiscoExterno,
    EventoCalendarioProximoError,
    LimiteGanhoDiarioError,
    ViolacaoCooldownError,
    ViolacaoHorarioOperacaoError,
    ViolacaoSLMaximoError,
    ViolacaoUnicaOrdemError,
)

__all__ = [
    "DomainError",
    "TradingError",
    "InvalidOrderError",
    "InsufficientCapitalError",
    "InvalidOperationError",
    "PositionNotFoundError",
    "RiskLimitExceededError",
    "InvalidPriceError",
    "InvalidQuantityError",
    "ModelError",
    "ModelNotTrainedError",
    "InvalidFeatureError",
    "BrokerError",
    "BrokerConnectionError",
    "OrderExecutionError",
    "DataError",
    "DataNotFoundError",
    "InvalidDataError",
    "MacroScoreError",
    "SymbolNotAvailableError",
    "ContractResolutionError",
    "InsufficientDataError",
    "ErroRiscoExterno",
    "ViolacaoCooldownError",
    "ViolacaoSLMaximoError",
    "ViolacaoUnicaOrdemError",
    "LimiteGanhoDiarioError",
    "ViolacaoHorarioOperacaoError",
    "EventoCalendarioProximoError",
]
